spring:
  profiles:
    active: dev
    
  
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/ntspb
    username: root
#---
#
#spring:
#  profiles: prod
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    password: admin
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: admin
#  
#---
#
#spring:
#  profiles: test
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: root
#    type: org.apache.tomcat.jdbc.pool.DataSource
#    url: jdbc:mysql://localhost:3306/ntspb
#    username: root
#
#---
#
#spring:
#  profiles: uat
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    password: admin
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: admin

